// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_test_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_test_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_test_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_test_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_test_2eproto;
class Example1;
struct Example1DefaultTypeInternal;
extern Example1DefaultTypeInternal _Example1_default_instance_;
class Example1_EmbeddedMessage;
struct Example1_EmbeddedMessageDefaultTypeInternal;
extern Example1_EmbeddedMessageDefaultTypeInternal _Example1_EmbeddedMessage_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Example1* Arena::CreateMaybeMessage<::Example1>(Arena*);
template<> ::Example1_EmbeddedMessage* Arena::CreateMaybeMessage<::Example1_EmbeddedMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Example1_EmbeddedMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Example1.EmbeddedMessage) */ {
 public:
  inline Example1_EmbeddedMessage() : Example1_EmbeddedMessage(nullptr) {}
  ~Example1_EmbeddedMessage() override;
  explicit constexpr Example1_EmbeddedMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Example1_EmbeddedMessage(const Example1_EmbeddedMessage& from);
  Example1_EmbeddedMessage(Example1_EmbeddedMessage&& from) noexcept
    : Example1_EmbeddedMessage() {
    *this = ::std::move(from);
  }

  inline Example1_EmbeddedMessage& operator=(const Example1_EmbeddedMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline Example1_EmbeddedMessage& operator=(Example1_EmbeddedMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Example1_EmbeddedMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const Example1_EmbeddedMessage* internal_default_instance() {
    return reinterpret_cast<const Example1_EmbeddedMessage*>(
               &_Example1_EmbeddedMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Example1_EmbeddedMessage& a, Example1_EmbeddedMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(Example1_EmbeddedMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Example1_EmbeddedMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Example1_EmbeddedMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Example1_EmbeddedMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Example1_EmbeddedMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Example1_EmbeddedMessage& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Example1_EmbeddedMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Example1.EmbeddedMessage";
  }
  protected:
  explicit Example1_EmbeddedMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStringValFieldNumber = 2,
    kInt32ValFieldNumber = 1,
  };
  // string stringVal = 2;
  void clear_stringval();
  const std::string& stringval() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stringval(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stringval();
  PROTOBUF_NODISCARD std::string* release_stringval();
  void set_allocated_stringval(std::string* stringval);
  private:
  const std::string& _internal_stringval() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stringval(const std::string& value);
  std::string* _internal_mutable_stringval();
  public:

  // int32 int32Val = 1;
  void clear_int32val();
  int32_t int32val() const;
  void set_int32val(int32_t value);
  private:
  int32_t _internal_int32val() const;
  void _internal_set_int32val(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Example1.EmbeddedMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stringval_;
  int32_t int32val_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_test_2eproto;
};
// -------------------------------------------------------------------

class Example1 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Example1) */ {
 public:
  inline Example1() : Example1(nullptr) {}
  ~Example1() override;
  explicit constexpr Example1(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Example1(const Example1& from);
  Example1(Example1&& from) noexcept
    : Example1() {
    *this = ::std::move(from);
  }

  inline Example1& operator=(const Example1& from) {
    CopyFrom(from);
    return *this;
  }
  inline Example1& operator=(Example1&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Example1& default_instance() {
    return *internal_default_instance();
  }
  static inline const Example1* internal_default_instance() {
    return reinterpret_cast<const Example1*>(
               &_Example1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Example1& a, Example1& b) {
    a.Swap(&b);
  }
  inline void Swap(Example1* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Example1* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Example1* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Example1>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Example1& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Example1& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Example1* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Example1";
  }
  protected:
  explicit Example1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Example1_EmbeddedMessage EmbeddedMessage;

  // accessors -------------------------------------------------------

  enum : int {
    kRepeatedInt32ValFieldNumber = 4,
    kRepeatedStringValFieldNumber = 5,
    kStringValFieldNumber = 1,
    kBytesValFieldNumber = 2,
    kEmbeddedExample1FieldNumber = 3,
  };
  // repeated int32 repeatedInt32Val = 4;
  int repeatedint32val_size() const;
  private:
  int _internal_repeatedint32val_size() const;
  public:
  void clear_repeatedint32val();
  private:
  int32_t _internal_repeatedint32val(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_repeatedint32val() const;
  void _internal_add_repeatedint32val(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_repeatedint32val();
  public:
  int32_t repeatedint32val(int index) const;
  void set_repeatedint32val(int index, int32_t value);
  void add_repeatedint32val(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      repeatedint32val() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_repeatedint32val();

  // repeated string repeatedStringVal = 5;
  int repeatedstringval_size() const;
  private:
  int _internal_repeatedstringval_size() const;
  public:
  void clear_repeatedstringval();
  const std::string& repeatedstringval(int index) const;
  std::string* mutable_repeatedstringval(int index);
  void set_repeatedstringval(int index, const std::string& value);
  void set_repeatedstringval(int index, std::string&& value);
  void set_repeatedstringval(int index, const char* value);
  void set_repeatedstringval(int index, const char* value, size_t size);
  std::string* add_repeatedstringval();
  void add_repeatedstringval(const std::string& value);
  void add_repeatedstringval(std::string&& value);
  void add_repeatedstringval(const char* value);
  void add_repeatedstringval(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& repeatedstringval() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_repeatedstringval();
  private:
  const std::string& _internal_repeatedstringval(int index) const;
  std::string* _internal_add_repeatedstringval();
  public:

  // optional string stringVal = 1;
  bool has_stringval() const;
  private:
  bool _internal_has_stringval() const;
  public:
  void clear_stringval();
  const std::string& stringval() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stringval(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stringval();
  PROTOBUF_NODISCARD std::string* release_stringval();
  void set_allocated_stringval(std::string* stringval);
  private:
  const std::string& _internal_stringval() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stringval(const std::string& value);
  std::string* _internal_mutable_stringval();
  public:

  // optional bytes bytesVal = 2;
  bool has_bytesval() const;
  private:
  bool _internal_has_bytesval() const;
  public:
  void clear_bytesval();
  const std::string& bytesval() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bytesval(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bytesval();
  PROTOBUF_NODISCARD std::string* release_bytesval();
  void set_allocated_bytesval(std::string* bytesval);
  private:
  const std::string& _internal_bytesval() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bytesval(const std::string& value);
  std::string* _internal_mutable_bytesval();
  public:

  // optional .Example1.EmbeddedMessage embeddedExample1 = 3;
  bool has_embeddedexample1() const;
  private:
  bool _internal_has_embeddedexample1() const;
  public:
  void clear_embeddedexample1();
  const ::Example1_EmbeddedMessage& embeddedexample1() const;
  PROTOBUF_NODISCARD ::Example1_EmbeddedMessage* release_embeddedexample1();
  ::Example1_EmbeddedMessage* mutable_embeddedexample1();
  void set_allocated_embeddedexample1(::Example1_EmbeddedMessage* embeddedexample1);
  private:
  const ::Example1_EmbeddedMessage& _internal_embeddedexample1() const;
  ::Example1_EmbeddedMessage* _internal_mutable_embeddedexample1();
  public:
  void unsafe_arena_set_allocated_embeddedexample1(
      ::Example1_EmbeddedMessage* embeddedexample1);
  ::Example1_EmbeddedMessage* unsafe_arena_release_embeddedexample1();

  // @@protoc_insertion_point(class_scope:Example1)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > repeatedint32val_;
  mutable std::atomic<int> _repeatedint32val_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> repeatedstringval_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stringval_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bytesval_;
  ::Example1_EmbeddedMessage* embeddedexample1_;
  friend struct ::TableStruct_test_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Example1_EmbeddedMessage

// int32 int32Val = 1;
inline void Example1_EmbeddedMessage::clear_int32val() {
  int32val_ = 0;
}
inline int32_t Example1_EmbeddedMessage::_internal_int32val() const {
  return int32val_;
}
inline int32_t Example1_EmbeddedMessage::int32val() const {
  // @@protoc_insertion_point(field_get:Example1.EmbeddedMessage.int32Val)
  return _internal_int32val();
}
inline void Example1_EmbeddedMessage::_internal_set_int32val(int32_t value) {
  
  int32val_ = value;
}
inline void Example1_EmbeddedMessage::set_int32val(int32_t value) {
  _internal_set_int32val(value);
  // @@protoc_insertion_point(field_set:Example1.EmbeddedMessage.int32Val)
}

// string stringVal = 2;
inline void Example1_EmbeddedMessage::clear_stringval() {
  stringval_.ClearToEmpty();
}
inline const std::string& Example1_EmbeddedMessage::stringval() const {
  // @@protoc_insertion_point(field_get:Example1.EmbeddedMessage.stringVal)
  return _internal_stringval();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Example1_EmbeddedMessage::set_stringval(ArgT0&& arg0, ArgT... args) {
 
 stringval_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Example1.EmbeddedMessage.stringVal)
}
inline std::string* Example1_EmbeddedMessage::mutable_stringval() {
  std::string* _s = _internal_mutable_stringval();
  // @@protoc_insertion_point(field_mutable:Example1.EmbeddedMessage.stringVal)
  return _s;
}
inline const std::string& Example1_EmbeddedMessage::_internal_stringval() const {
  return stringval_.Get();
}
inline void Example1_EmbeddedMessage::_internal_set_stringval(const std::string& value) {
  
  stringval_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Example1_EmbeddedMessage::_internal_mutable_stringval() {
  
  return stringval_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Example1_EmbeddedMessage::release_stringval() {
  // @@protoc_insertion_point(field_release:Example1.EmbeddedMessage.stringVal)
  return stringval_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Example1_EmbeddedMessage::set_allocated_stringval(std::string* stringval) {
  if (stringval != nullptr) {
    
  } else {
    
  }
  stringval_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), stringval,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (stringval_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    stringval_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Example1.EmbeddedMessage.stringVal)
}

// -------------------------------------------------------------------

// Example1

// optional string stringVal = 1;
inline bool Example1::_internal_has_stringval() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Example1::has_stringval() const {
  return _internal_has_stringval();
}
inline void Example1::clear_stringval() {
  stringval_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Example1::stringval() const {
  // @@protoc_insertion_point(field_get:Example1.stringVal)
  return _internal_stringval();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Example1::set_stringval(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 stringval_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Example1.stringVal)
}
inline std::string* Example1::mutable_stringval() {
  std::string* _s = _internal_mutable_stringval();
  // @@protoc_insertion_point(field_mutable:Example1.stringVal)
  return _s;
}
inline const std::string& Example1::_internal_stringval() const {
  return stringval_.Get();
}
inline void Example1::_internal_set_stringval(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  stringval_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Example1::_internal_mutable_stringval() {
  _has_bits_[0] |= 0x00000001u;
  return stringval_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Example1::release_stringval() {
  // @@protoc_insertion_point(field_release:Example1.stringVal)
  if (!_internal_has_stringval()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = stringval_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (stringval_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    stringval_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Example1::set_allocated_stringval(std::string* stringval) {
  if (stringval != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  stringval_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), stringval,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (stringval_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    stringval_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Example1.stringVal)
}

// optional bytes bytesVal = 2;
inline bool Example1::_internal_has_bytesval() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Example1::has_bytesval() const {
  return _internal_has_bytesval();
}
inline void Example1::clear_bytesval() {
  bytesval_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Example1::bytesval() const {
  // @@protoc_insertion_point(field_get:Example1.bytesVal)
  return _internal_bytesval();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Example1::set_bytesval(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 bytesval_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Example1.bytesVal)
}
inline std::string* Example1::mutable_bytesval() {
  std::string* _s = _internal_mutable_bytesval();
  // @@protoc_insertion_point(field_mutable:Example1.bytesVal)
  return _s;
}
inline const std::string& Example1::_internal_bytesval() const {
  return bytesval_.Get();
}
inline void Example1::_internal_set_bytesval(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  bytesval_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Example1::_internal_mutable_bytesval() {
  _has_bits_[0] |= 0x00000002u;
  return bytesval_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Example1::release_bytesval() {
  // @@protoc_insertion_point(field_release:Example1.bytesVal)
  if (!_internal_has_bytesval()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = bytesval_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (bytesval_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    bytesval_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Example1::set_allocated_bytesval(std::string* bytesval) {
  if (bytesval != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  bytesval_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), bytesval,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (bytesval_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    bytesval_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Example1.bytesVal)
}

// optional .Example1.EmbeddedMessage embeddedExample1 = 3;
inline bool Example1::_internal_has_embeddedexample1() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || embeddedexample1_ != nullptr);
  return value;
}
inline bool Example1::has_embeddedexample1() const {
  return _internal_has_embeddedexample1();
}
inline void Example1::clear_embeddedexample1() {
  if (embeddedexample1_ != nullptr) embeddedexample1_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::Example1_EmbeddedMessage& Example1::_internal_embeddedexample1() const {
  const ::Example1_EmbeddedMessage* p = embeddedexample1_;
  return p != nullptr ? *p : reinterpret_cast<const ::Example1_EmbeddedMessage&>(
      ::_Example1_EmbeddedMessage_default_instance_);
}
inline const ::Example1_EmbeddedMessage& Example1::embeddedexample1() const {
  // @@protoc_insertion_point(field_get:Example1.embeddedExample1)
  return _internal_embeddedexample1();
}
inline void Example1::unsafe_arena_set_allocated_embeddedexample1(
    ::Example1_EmbeddedMessage* embeddedexample1) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(embeddedexample1_);
  }
  embeddedexample1_ = embeddedexample1;
  if (embeddedexample1) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Example1.embeddedExample1)
}
inline ::Example1_EmbeddedMessage* Example1::release_embeddedexample1() {
  _has_bits_[0] &= ~0x00000004u;
  ::Example1_EmbeddedMessage* temp = embeddedexample1_;
  embeddedexample1_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Example1_EmbeddedMessage* Example1::unsafe_arena_release_embeddedexample1() {
  // @@protoc_insertion_point(field_release:Example1.embeddedExample1)
  _has_bits_[0] &= ~0x00000004u;
  ::Example1_EmbeddedMessage* temp = embeddedexample1_;
  embeddedexample1_ = nullptr;
  return temp;
}
inline ::Example1_EmbeddedMessage* Example1::_internal_mutable_embeddedexample1() {
  _has_bits_[0] |= 0x00000004u;
  if (embeddedexample1_ == nullptr) {
    auto* p = CreateMaybeMessage<::Example1_EmbeddedMessage>(GetArenaForAllocation());
    embeddedexample1_ = p;
  }
  return embeddedexample1_;
}
inline ::Example1_EmbeddedMessage* Example1::mutable_embeddedexample1() {
  ::Example1_EmbeddedMessage* _msg = _internal_mutable_embeddedexample1();
  // @@protoc_insertion_point(field_mutable:Example1.embeddedExample1)
  return _msg;
}
inline void Example1::set_allocated_embeddedexample1(::Example1_EmbeddedMessage* embeddedexample1) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete embeddedexample1_;
  }
  if (embeddedexample1) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::Example1_EmbeddedMessage>::GetOwningArena(embeddedexample1);
    if (message_arena != submessage_arena) {
      embeddedexample1 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, embeddedexample1, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  embeddedexample1_ = embeddedexample1;
  // @@protoc_insertion_point(field_set_allocated:Example1.embeddedExample1)
}

// repeated int32 repeatedInt32Val = 4;
inline int Example1::_internal_repeatedint32val_size() const {
  return repeatedint32val_.size();
}
inline int Example1::repeatedint32val_size() const {
  return _internal_repeatedint32val_size();
}
inline void Example1::clear_repeatedint32val() {
  repeatedint32val_.Clear();
}
inline int32_t Example1::_internal_repeatedint32val(int index) const {
  return repeatedint32val_.Get(index);
}
inline int32_t Example1::repeatedint32val(int index) const {
  // @@protoc_insertion_point(field_get:Example1.repeatedInt32Val)
  return _internal_repeatedint32val(index);
}
inline void Example1::set_repeatedint32val(int index, int32_t value) {
  repeatedint32val_.Set(index, value);
  // @@protoc_insertion_point(field_set:Example1.repeatedInt32Val)
}
inline void Example1::_internal_add_repeatedint32val(int32_t value) {
  repeatedint32val_.Add(value);
}
inline void Example1::add_repeatedint32val(int32_t value) {
  _internal_add_repeatedint32val(value);
  // @@protoc_insertion_point(field_add:Example1.repeatedInt32Val)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Example1::_internal_repeatedint32val() const {
  return repeatedint32val_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
Example1::repeatedint32val() const {
  // @@protoc_insertion_point(field_list:Example1.repeatedInt32Val)
  return _internal_repeatedint32val();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Example1::_internal_mutable_repeatedint32val() {
  return &repeatedint32val_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
Example1::mutable_repeatedint32val() {
  // @@protoc_insertion_point(field_mutable_list:Example1.repeatedInt32Val)
  return _internal_mutable_repeatedint32val();
}

// repeated string repeatedStringVal = 5;
inline int Example1::_internal_repeatedstringval_size() const {
  return repeatedstringval_.size();
}
inline int Example1::repeatedstringval_size() const {
  return _internal_repeatedstringval_size();
}
inline void Example1::clear_repeatedstringval() {
  repeatedstringval_.Clear();
}
inline std::string* Example1::add_repeatedstringval() {
  std::string* _s = _internal_add_repeatedstringval();
  // @@protoc_insertion_point(field_add_mutable:Example1.repeatedStringVal)
  return _s;
}
inline const std::string& Example1::_internal_repeatedstringval(int index) const {
  return repeatedstringval_.Get(index);
}
inline const std::string& Example1::repeatedstringval(int index) const {
  // @@protoc_insertion_point(field_get:Example1.repeatedStringVal)
  return _internal_repeatedstringval(index);
}
inline std::string* Example1::mutable_repeatedstringval(int index) {
  // @@protoc_insertion_point(field_mutable:Example1.repeatedStringVal)
  return repeatedstringval_.Mutable(index);
}
inline void Example1::set_repeatedstringval(int index, const std::string& value) {
  repeatedstringval_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:Example1.repeatedStringVal)
}
inline void Example1::set_repeatedstringval(int index, std::string&& value) {
  repeatedstringval_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:Example1.repeatedStringVal)
}
inline void Example1::set_repeatedstringval(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  repeatedstringval_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Example1.repeatedStringVal)
}
inline void Example1::set_repeatedstringval(int index, const char* value, size_t size) {
  repeatedstringval_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Example1.repeatedStringVal)
}
inline std::string* Example1::_internal_add_repeatedstringval() {
  return repeatedstringval_.Add();
}
inline void Example1::add_repeatedstringval(const std::string& value) {
  repeatedstringval_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Example1.repeatedStringVal)
}
inline void Example1::add_repeatedstringval(std::string&& value) {
  repeatedstringval_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Example1.repeatedStringVal)
}
inline void Example1::add_repeatedstringval(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  repeatedstringval_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Example1.repeatedStringVal)
}
inline void Example1::add_repeatedstringval(const char* value, size_t size) {
  repeatedstringval_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Example1.repeatedStringVal)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Example1::repeatedstringval() const {
  // @@protoc_insertion_point(field_list:Example1.repeatedStringVal)
  return repeatedstringval_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Example1::mutable_repeatedstringval() {
  // @@protoc_insertion_point(field_mutable_list:Example1.repeatedStringVal)
  return &repeatedstringval_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_test_2eproto
